## About Numpy- Numeric python ( Python Library to work for array)


# NumPy (Numerical Python)
1. NumPy is the fundamental package for scientific computing in Python.
2. It is a Python library that provides a multidimensional array object, various derived objects such as matrices etc.
3. An assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting,  basic linear algebra, basic statistical operations, and many more.
4. At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance. 

## NumPy Array vs. Python Sequences

NumPy arrays have a fixed size at creation, NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

## Installing and Importing NumPy

If we use pip, we can install NumPy as : pip install numpy
Once the package has been installed, it need to be imported.

In [1]:
#pip install numpy
import numpy as np

###Sum of two lists ( here it is concatenation only)

In [16]:
a = [1,2,3,4,5]
b = [10,20,30,40,50]
c = a + b
print(c)

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]


### Array
* Group of homogenous data
* It can be multidimentional

### Sum of two array ( Here + means calculation)

In [6]:
a = np.array([1,2,3,4,5])
b = np.array([12,20,30,40,50])
c = a + b
print(c)
print(a)

[13 22 33 44 55]
[1 2 3 4 5]


In [7]:
b = np.array([10,20,30,40,50])
c = b+120
print(c)

[130 140 150 160 170]


In [8]:
a1 = np.array([1.,2.,3.,4.,5.,6.,7.,8.,9.,10.])
a2 = np.array([[1,2,3,4,5,6,7,8,9,10]]) # this is 2 D, list of list
a3 = np.array([[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10]])# three lists ( 2D array with 3 elements)
a4 = np.array([[[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10]]])
a5 = np.array([[[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10]],
              [[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10]]])
print(a2)

[[ 1  2  3  4  5  6  7  8  9 10]]


In [9]:
print(a1)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [10]:
print(a5)

[[[ 1  2  3  4  5  6  7  8  9 10]
  [ 1  2  3  4  5  6  7  8  9 10]
  [ 1  2  3  4  5  6  7  8  9 10]]

 [[ 1  2  3  4  5  6  7  8  9 10]
  [ 1  2  3  4  5  6  7  8  9 10]
  [ 1  2  3  4  5  6  7  8  9 10]]]


## No of brackets tells about dimension

In [11]:
print(len(a1))
print(len(a2))
print(len(a3))
print(len(a4))
print(len(a5))

10
1
3
1
2


### Check the above output|

#### length of 2d array = no of 1d array
#### length of 3d array = no of 2d array

# Attributes of Array

In [12]:
print(a1.shape)
print(a2.shape)
print(a3.shape)
print(a4.shape) # one (3 x 10) Two dimensional array with 3 rows and 10 columns
print(a5.shape) # two (3 x 10) Two dimensional array with 3 rows and 10 columns

(10,)
(1, 10)
(3, 10)
(1, 3, 10)
(2, 3, 10)


In [13]:
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)
print(a4.ndim)
print(a5.ndim)

1
2
2
3
3


### dtype gives the data type

In [14]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)
print(a4.dtype)
print(a5.dtype)

float64
int32
int32
int32
int32


#### Slicing of array

# a[:, :]  # rows and column

In [15]:
#np.random.seed(1)
x=np.random.randint(1,100,(10,10))
x

array([[30, 96, 56, 33, 49, 43, 38, 91, 54, 24],
       [62, 32, 71, 91, 37, 50, 98, 47, 61, 36],
       [92, 71, 96,  7, 93, 18, 50, 59, 79, 17],
       [59, 37, 16, 62, 92, 67, 12, 22, 15, 93],
       [ 4,  3, 14, 40, 62, 45, 23, 14, 17, 91],
       [67, 94,  6, 83, 20, 16, 15,  5, 71, 78],
       [53,  2, 20, 40, 46, 58, 12, 69, 47, 73],
       [27, 59, 19, 42,  7, 98, 17, 82, 29, 52],
       [67, 36,  1, 22, 14, 27, 42, 73, 45, 62],
       [60, 43, 93, 96,  5, 19,  2, 98, 19, 31]])

In [16]:
x[:,:]

array([[30, 96, 56, 33, 49, 43, 38, 91, 54, 24],
       [62, 32, 71, 91, 37, 50, 98, 47, 61, 36],
       [92, 71, 96,  7, 93, 18, 50, 59, 79, 17],
       [59, 37, 16, 62, 92, 67, 12, 22, 15, 93],
       [ 4,  3, 14, 40, 62, 45, 23, 14, 17, 91],
       [67, 94,  6, 83, 20, 16, 15,  5, 71, 78],
       [53,  2, 20, 40, 46, 58, 12, 69, 47, 73],
       [27, 59, 19, 42,  7, 98, 17, 82, 29, 52],
       [67, 36,  1, 22, 14, 27, 42, 73, 45, 62],
       [60, 43, 93, 96,  5, 19,  2, 98, 19, 31]])

In [17]:
print(x.ndim)

2


In [18]:
print(x.shape)

(10, 10)


In [19]:
x[:, 4:8]

array([[49, 43, 38, 91],
       [37, 50, 98, 47],
       [93, 18, 50, 59],
       [92, 67, 12, 22],
       [62, 45, 23, 14],
       [20, 16, 15,  5],
       [46, 58, 12, 69],
       [ 7, 98, 17, 82],
       [14, 27, 42, 73],
       [ 5, 19,  2, 98]])

In [20]:
x[1,4]

37

In [21]:
x[3:6,:]

array([[59, 37, 16, 62, 92, 67, 12, 22, 15, 93],
       [ 4,  3, 14, 40, 62, 45, 23, 14, 17, 91],
       [67, 94,  6, 83, 20, 16, 15,  5, 71, 78]])

In [36]:
x[6:,:]

array([[21, 49, 23, 14, 98, 54, 85, 11, 97, 56],
       [62, 57, 90, 22, 97, 84, 26, 15, 14, 85],
       [44,  7, 78, 57, 60, 16, 25, 10, 67, 72],
       [54, 70, 37, 22, 41, 78, 92, 50, 48, 78]])

In [22]:
x[1][4]

37

#### Array Functions / Methods

In [23]:
#np.random.seed(2)
x=np.random.randint(1,100,(5,6))
x

array([[95, 59, 63, 28, 90, 32],
       [ 5, 73, 68, 63, 51, 87],
       [48, 11, 59, 46, 29, 34],
       [19, 26, 97, 59,  4, 51],
       [76,  6, 49, 54, 96, 37]])

In [24]:
print(x.sum())
print(x.sum(axis=0))  ### column wise sum
print(x.sum(axis=1))   ## row wise sum

1515
[243 175 336 250 270 241]
[367 347 227 256 318]


In [25]:
print(x.mean())
print(x.mean(axis=0)) 
print(x.mean(axis=1))

50.5
[48.6 35.  67.2 50.  54.  48.2]
[61.16666667 57.83333333 37.83333333 42.66666667 53.        ]


In [26]:
print(x.min())
print(x.min(axis=0)) 
print(x.min(axis=1))

4
[ 5  6 49 28  4 32]
[28  5 11  4  6]


In [27]:
print(x.max())
print(x.max(axis=0)) 
print(x.max(axis=1))

97
[95 73 97 63 96 87]
[95 87 59 97 96]


In [29]:
print(x.argmax())
print(x.argmax(axis=0)) 
print(x.argmax(axis=1))

20
[0 1 3 1 4 1]
[0 5 2 2 4]


## what is this output

In [31]:
x

array([[95, 59, 63, 28, 90, 32],
       [ 5, 73, 68, 63, 51, 87],
       [48, 11, 59, 46, 29, 34],
       [19, 26, 97, 59,  4, 51],
       [76,  6, 49, 54, 96, 37]])

In [32]:
print(x.argmin())
print(x.argmin(axis=0)) 
print(x.argmin(axis=1))

22
[1 4 4 0 3 0]
[3 0 1 4 1]


In [33]:
x_1 = x.astype('float')
x_1

array([[95., 59., 63., 28., 90., 32.],
       [ 5., 73., 68., 63., 51., 87.],
       [48., 11., 59., 46., 29., 34.],
       [19., 26., 97., 59.,  4., 51.],
       [76.,  6., 49., 54., 96., 37.]])

In [34]:
x_1 = x.astype('complex')
x_1

array([[95.+0.j, 59.+0.j, 63.+0.j, 28.+0.j, 90.+0.j, 32.+0.j],
       [ 5.+0.j, 73.+0.j, 68.+0.j, 63.+0.j, 51.+0.j, 87.+0.j],
       [48.+0.j, 11.+0.j, 59.+0.j, 46.+0.j, 29.+0.j, 34.+0.j],
       [19.+0.j, 26.+0.j, 97.+0.j, 59.+0.j,  4.+0.j, 51.+0.j],
       [76.+0.j,  6.+0.j, 49.+0.j, 54.+0.j, 96.+0.j, 37.+0.j]])

In [35]:
x.shape

(5, 6)

In [38]:
x

array([[95, 59, 63, 28, 90, 32],
       [ 5, 73, 68, 63, 51, 87],
       [48, 11, 59, 46, 29, 34],
       [19, 26, 97, 59,  4, 51],
       [76,  6, 49, 54, 96, 37]])

## Reshaping ( currently x is 5 x 6)

In [43]:
x_1 = x.reshape(30)
x_2 = x.reshape((10,3))    ## 6,5 | 1,30 | 30,1 | 2,15 | 15,2 | 10,3 | 3,10
x_3 = x.reshape([5,2,3])

ValueError: cannot reshape array of size 30 into shape (10,4)

In [40]:
x_1

array([95, 59, 63, 28, 90, 32,  5, 73, 68, 63, 51, 87, 48, 11, 59, 46, 29,
       34, 19, 26, 97, 59,  4, 51, 76,  6, 49, 54, 96, 37])

In [41]:
x_2

array([[95, 59, 63],
       [28, 90, 32],
       [ 5, 73, 68],
       [63, 51, 87],
       [48, 11, 59],
       [46, 29, 34],
       [19, 26, 97],
       [59,  4, 51],
       [76,  6, 49],
       [54, 96, 37]])

In [42]:
x_3  # there will be 5 ; 2 x3 arrays

array([[[95, 59, 63],
        [28, 90, 32]],

       [[ 5, 73, 68],
        [63, 51, 87]],

       [[48, 11, 59],
        [46, 29, 34]],

       [[19, 26, 97],
        [59,  4, 51]],

       [[76,  6, 49],
        [54, 96, 37]]])

In [55]:
x = np.array([335.44444,225.33333,222.4444])
x

array([335.44444, 225.33333, 222.4444 ])

In [56]:
np.round(x)

array([335., 225., 222.])

In [57]:
np.round(x,2)

array([335.44, 225.33, 222.44])

In [58]:
x5 = np.array([45,32,323,22,22,22,45,45,333,323,222])
x5

array([ 45,  32, 323,  22,  22,  22,  45,  45, 333, 323, 222])

In [59]:
np.unique(x5)


array([ 22,  32,  45, 222, 323, 333])

In [60]:
np.unique(x5, return_counts= True)


(array([ 22,  32,  45, 222, 323, 333]), array([3, 1, 3, 1, 2, 1], dtype=int64))

#### Random Numbers

In [61]:
np.random.randint(100)

24

In [62]:
np.random.seed(100)     ### any value between 0 to 2**32 -1 
np.random.randint(100)

8

In [63]:
np.random.randint(100,500,(10,4))

array([[380, 423, 459, 443],
       [179, 494, 450, 454],
       [153, 166, 326, 114],
       [390, 340, 380, 243],
       [328, 463, 416, 158],
       [237, 193, 186, 486],
       [255, 464, 488, 485],
       [241, 345, 311, 200],
       [104, 191, 423, 235],
       [149, 293, 417, 370]])

In [64]:
np.random.randint(100,500,(3,4,2))

array([[[283, 351],
        [436, 102],
        [477, 205],
        [163, 281]],

       [[383, 412],
        [338, 469],
        [403, 267],
        [465, 394]],

       [[272, 374],
        [292, 302],
        [373, 172],
        [113, 206]]])

In [65]:
np.random.randint(100,500,10)

array([130, 117, 153, 168, 447, 281, 434, 100, 113, 285])

In [66]:
y=np.random.uniform(100,500,10)
y

array([214.35827616, 440.95803514, 490.00259744, 453.9413174 ,
       243.80313757, 339.54357835, 241.91824466, 236.07608615,
       171.2323958 , 195.07768345])

In [67]:
y.mean()

302.69113521265257

In [68]:
np.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [69]:
np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [70]:
p=np.random.randint(0,20,10)
p

array([ 6,  2, 10, 18, 13, 12,  1,  6, 10,  0])

In [10]:
p.var()

26.49

In [71]:
p.std()

5.528109984434101

In [19]:
np.arange(5,25,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [20]:
np.arange(5,25,2).reshape(2,5)

array([[ 5,  7,  9, 11, 13],
       [15, 17, 19, 21, 23]])

In [72]:
np.random.seed(2)
x = np.random.randint(1,11,(2,5))
x

array([[9, 9, 7, 3, 9],
       [8, 3, 2, 6, 5]])

In [73]:
np.random.seed(5)
y = np.random.randint(1,11,(2,5))
y

array([[ 4,  7,  7,  1, 10],
       [ 9,  5,  8,  1,  1]])

In [25]:
np.add(x,y)

array([[13, 16, 14,  4, 19],
       [17,  8, 10,  7,  6]])

In [27]:
np.subtract(x,y)

array([[ 5,  2,  0,  2, -1],
       [-1, -2, -6,  5,  4]])

In [29]:
np.random.seed(7)
z = np.random.randint(1,11,(5,2))
z

array([[ 5, 10],
       [ 7,  4],
       [ 4,  8],
       [ 8, 10],
       [ 8,  9]])

In [30]:
np.matmul(x,z)

array([[232, 293],
       [157, 213]])