In [42]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA

In [43]:
# Load the sample dataset
df = pd.read_csv("Iris.csv")

In [44]:
df

Id  SepalLength  SepalWidth  PetalLength  PetalWidth           Class
0      1          5.1         3.5          1.4         0.2     Iris-setosa
1      2          4.9         3.0          1.4         0.2     Iris-setosa
2      3          4.7         3.2          1.3         0.2     Iris-setosa
3      4          4.6         3.1          1.5         0.2     Iris-setosa
4      5          5.0         3.6          1.4         0.2     Iris-setosa
..   ...          ...         ...          ...         ...             ...
145  146          6.7         3.0          5.2         2.3  Iris-virginica
146  147          6.3         2.5          5.0         1.9  Iris-virginica
147  148          6.5         3.0          5.2         2.0  Iris-virginica
148  149          6.2         3.4          5.4         2.3  Iris-virginica
149  150          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 6 columns]

In [45]:
df.shape

(150, 6)

In [47]:
# Standardize the data
X = df[['SepalLength', 'SepalWidth','PetalLength', 'PetalWidth']].values
X = (X - np.mean(X, axis=0)) / np.std(X, axis=0)
X

array([[-9.00681170e-01,  1.03205722e+00, -1.34127240e+00,
        -1.31297673e+00],
       [-1.14301691e+00, -1.24957601e-01, -1.34127240e+00,
        -1.31297673e+00],
       [-1.38535265e+00,  3.37848329e-01, -1.39813811e+00,
        -1.31297673e+00],
       [-1.50652052e+00,  1.06445364e-01, -1.28440670e+00,
        -1.31297673e+00],
       [-1.02184904e+00,  1.26346019e+00, -1.34127240e+00,
        -1.31297673e+00],
       [-5.37177559e-01,  1.95766909e+00, -1.17067529e+00,
        -1.05003079e+00],
       [-1.50652052e+00,  8.00654259e-01, -1.34127240e+00,
        -1.18150376e+00],
       [-1.02184904e+00,  8.00654259e-01, -1.28440670e+00,
        -1.31297673e+00],
       [-1.74885626e+00, -3.56360566e-01, -1.34127240e+00,
        -1.31297673e+00],
       [-1.14301691e+00,  1.06445364e-01, -1.28440670e+00,
        -1.44444970e+00],
       [-5.37177559e-01,  1.49486315e+00, -1.28440670e+00,
        -1.31297673e+00],
       [-1.26418478e+00,  8.00654259e-01, -1.22754100e+00,
      

In [18]:
# Standardize the data
#P= df[['SepalLength', 'SepalWidth','PetalLength', 'PetalWidth']]
#P = (P - np.mean(P, axis=0)) / np.std(P, axis=0)
#P

In [49]:
# Calculate Principal Components
pca = PCA()
Z = pca.fit_transform(X)
Z

array([[-2.26454173e+00,  5.05703903e-01, -1.21943348e-01,
        -2.30733235e-02],
       [-2.08642550e+00, -6.55404729e-01, -2.27250832e-01,
        -1.03208244e-01],
       [-2.36795045e+00, -3.18477311e-01,  5.14796236e-02,
        -2.78252250e-02],
       [-2.30419716e+00, -5.75367713e-01,  9.88604444e-02,
         6.63114622e-02],
       [-2.38877749e+00,  6.74767397e-01,  2.14278490e-02,
         3.73972870e-02],
       [-2.07053681e+00,  1.51854856e+00,  3.06842583e-02,
        -4.39877494e-03],
       [-2.44571134e+00,  7.45626750e-02,  3.42197636e-01,
         3.80965668e-02],
       [-2.23384186e+00,  2.47613932e-01, -8.25744645e-02,
         2.55051623e-02],
       [-2.34195768e+00, -1.09514636e+00,  1.53562399e-01,
         2.67938291e-02],
       [-2.18867576e+00, -4.48629048e-01, -2.46559522e-01,
         3.99073035e-02],
       [-2.16348656e+00,  1.07059558e+00, -2.64009373e-01,
        -1.53011377e-02],
       [-2.32737775e+00,  1.58587455e-01,  1.00165616e-01,
      

In [50]:
Y=pd.DataFrame(Z)
Y

0         1         2         3
0   -2.264542  0.505704 -0.121943 -0.023073
1   -2.086426 -0.655405 -0.227251 -0.103208
2   -2.367950 -0.318477  0.051480 -0.027825
3   -2.304197 -0.575368  0.098860  0.066311
4   -2.388777  0.674767  0.021428  0.037397
..        ...       ...       ...       ...
145  1.870522  0.382822  0.254532 -0.388890
146  1.558492 -0.905314 -0.025382 -0.221322
147  1.520845  0.266795  0.179277 -0.118903
148  1.376391  1.016362  0.931405 -0.024146
149  0.959299 -0.022284  0.528794  0.163676

[150 rows x 4 columns]

In [51]:
# Access the explained variance ratio for each Principal Component
explained_variance = pca.explained_variance_ratio_

print("Explained variance for each Principal Component:")
print(explained_variance)

Explained variance for each Principal Component:
[0.72770452 0.23030523 0.03683832 0.00515193]


In [52]:
pca = PCA(n_components=3)



In [53]:
# Fit and transform the data
X_reduced = pca.fit_transform(Y)

In [54]:
print(X_reduced)

[[-2.26454173e+00  5.05703903e-01 -1.21943348e-01]
 [-2.08642550e+00 -6.55404729e-01 -2.27250832e-01]
 [-2.36795045e+00 -3.18477311e-01  5.14796236e-02]
 [-2.30419716e+00 -5.75367713e-01  9.88604444e-02]
 [-2.38877749e+00  6.74767397e-01  2.14278490e-02]
 [-2.07053681e+00  1.51854856e+00  3.06842583e-02]
 [-2.44571134e+00  7.45626750e-02  3.42197636e-01]
 [-2.23384186e+00  2.47613932e-01 -8.25744645e-02]
 [-2.34195768e+00 -1.09514636e+00  1.53562399e-01]
 [-2.18867576e+00 -4.48629048e-01 -2.46559522e-01]
 [-2.16348656e+00  1.07059558e+00 -2.64009373e-01]
 [-2.32737775e+00  1.58587455e-01  1.00165616e-01]
 [-2.22408272e+00 -7.09118158e-01 -2.23214514e-01]
 [-2.63971626e+00 -9.38281982e-01  1.89570030e-01]
 [-2.19229151e+00  1.88997851e+00 -4.69480095e-01]
 [-2.25146521e+00  2.72237108e+00  3.26037967e-02]
 [-2.20275048e+00  1.51375028e+00 -1.36349158e-03]
 [-2.19017916e+00  5.14304308e-01 -3.86155949e-02]
 [-1.89407429e+00  1.43111071e+00 -3.70742834e-01]
 [-2.33994907e+00  1.15803343e+